YouTube:  1
Vimeo:    2

Awesome:  1
Skip:     0
Dislike:  -1

prime:  2654435761
max_id: 2147483647

worst_allowed:  -5
newly_submitted: 3

google_analytics:
  development: UA-XXXXXXXX-X
  test: UA-XXXXXXXX-Y
  staging: UA-XXXXXXXX-Z
  production: UA-38284101-1